do $$
begin
  create type tarot_orientation as enum ('upright', 'reversed');
exception
  when duplicate_object then null;
end
$$;

create table if not exists tarot_card_profiles (
  card_id smallint primary key check (card_id between 0 and 77),
  name_ko text not null check (length(trim(name_ko)) > 0),
  name_en text not null check (length(trim(name_en)) > 0),
  arcana text not null check (arcana in ('major', 'minor')),
  suit text check (suit is null or suit in ('wands', 'cups', 'swords', 'pentacles')),
  rank text not null check (length(trim(rank)) > 0),
  upright_keywords text[] not null check (cardinality(upright_keywords) > 0),
  reversed_keywords text[] not null check (cardinality(reversed_keywords) > 0),
  upright_one_line text not null check (length(trim(upright_one_line)) > 0),
  reversed_one_line text not null check (length(trim(reversed_one_line)) > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (
    (arcana = 'major' and suit is null)
    or (arcana = 'minor' and suit is not null)
  )
);

create table if not exists tarot_base_interpretations (
  card_id smallint primary key
    references tarot_card_profiles(card_id) on delete cascade,
  upright jsonb not null check (
    jsonb_typeof(upright) = 'object'
    and upright ?& array[
      'overview', 'current_situation', 'emotion', 'cause', 'future',
      'advice', 'love', 'career', 'relationships', 'other'
    ]
  ),
  reversed jsonb not null check (
    jsonb_typeof(reversed) = 'object'
    and reversed ?& array[
      'overview', 'current_situation', 'emotion', 'cause', 'future',
      'advice', 'love', 'career', 'relationships', 'other'
    ]
  ),
  source_files text[] not null check (cardinality(source_files) > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists tarot_topic_readings (
  id bigint generated by default as identity primary key,
  card_id smallint not null
    references tarot_card_profiles(card_id) on delete cascade,
  topic_id text not null check (topic_id in (
    'their-feelings',
    'new-love',
    'relationship-flow',
    'career',
    'money',
    'relationships',
    'decision',
    'personal-flow'
  )),
  orientation tarot_orientation not null,
  headline text not null check (length(trim(headline)) > 0),
  core_message text not null check (length(trim(core_message)) > 0),
  emotional_layer text not null check (length(trim(emotional_layer)) > 0),
  hidden_context text not null check (length(trim(hidden_context)) > 0),
  challenge text not null check (length(trim(challenge)) > 0),
  opportunity text not null check (length(trim(opportunity)) > 0),
  near_future text not null check (length(trim(near_future)) > 0),
  advice text not null check (length(trim(advice)) > 0),
  reflection_question text not null check (length(trim(reflection_question)) > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (card_id, topic_id, orientation)
);

create or replace function set_tarot_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_tarot_card_profiles_updated_at on tarot_card_profiles;
create trigger set_tarot_card_profiles_updated_at
before update on tarot_card_profiles
for each row execute function set_tarot_updated_at();

drop trigger if exists set_tarot_base_interpretations_updated_at on tarot_base_interpretations;
create trigger set_tarot_base_interpretations_updated_at
before update on tarot_base_interpretations
for each row execute function set_tarot_updated_at();

drop trigger if exists set_tarot_topic_readings_updated_at on tarot_topic_readings;
create trigger set_tarot_topic_readings_updated_at
before update on tarot_topic_readings
for each row execute function set_tarot_updated_at();

alter table tarot_card_profiles enable row level security;
alter table tarot_base_interpretations enable row level security;
alter table tarot_topic_readings enable row level security;

drop policy if exists "profiles are publicly readable" on tarot_card_profiles;
create policy "profiles are publicly readable"
on tarot_card_profiles
for select
to anon, authenticated
using (true);

drop policy if exists "topic readings are publicly readable" on tarot_topic_readings;
create policy "topic readings are publicly readable"
on tarot_topic_readings
for select
to anon, authenticated
using (true);
