create table if not exists tarot_position_readings (
  id bigint generated by default as identity primary key,
  card_id smallint not null
    references tarot_card_profiles(card_id) on delete cascade,
  topic_id text not null check (topic_id in (
    'their-feelings',
    'new-love',
    'relationship-flow',
    'career',
    'money',
    'relationships',
    'decision',
    'personal-flow'
  )),
  orientation tarot_orientation not null,
  reading_type text not null check (reading_type in ('one', 'three', 'celtic', 'horoscope')),
  layout_id text not null check (length(trim(layout_id)) > 0),
  position_id text not null check (length(trim(position_id)) > 0),
  headline text not null check (length(trim(headline)) > 0),
  summary text not null check (length(trim(summary)) > 0),
  detail text not null check (length(trim(detail)) > 0),
  advice text not null check (length(trim(advice)) > 0),
  reflection_question text not null check (length(trim(reflection_question)) > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (card_id, topic_id, orientation, reading_type, layout_id, position_id)
);

create index if not exists tarot_position_readings_lookup_idx
on tarot_position_readings (reading_type, layout_id, position_id, topic_id, card_id, orientation);

drop trigger if exists set_tarot_position_readings_updated_at on tarot_position_readings;
create trigger set_tarot_position_readings_updated_at
before update on tarot_position_readings
for each row execute function set_tarot_updated_at();

alter table tarot_position_readings enable row level security;

drop policy if exists "position readings are publicly readable" on tarot_position_readings;
create policy "position readings are publicly readable"
on tarot_position_readings
for select
to anon, authenticated
using (true);

with position_definitions (reading_type, layout_id, position_id, label, role) as (
  values
    ('one', 'single', 'message', '오늘의 메시지', 'message'),
    ('three', 'timeline', 'past', '과거', 'past'),
    ('three', 'timeline', 'present', '현재', 'present'),
    ('three', 'timeline', 'future', '미래', 'future'),
    ('three', 'problem', 'situation', '상황', 'present'),
    ('three', 'problem', 'obstacle', '장애물', 'blocker'),
    ('three', 'problem', 'advice', '조언', 'advice'),
    ('three', 'relationship', 'self', '나', 'context'),
    ('three', 'relationship', 'other', '상대', 'context'),
    ('three', 'relationship', 'connection', '관계', 'present'),
    ('three', 'choice', 'option-a', '선택 A', 'context'),
    ('three', 'choice', 'option-b', '선택 B', 'context'),
    ('three', 'choice', 'decision-key', '결정의 열쇠', 'advice'),
    ('three', 'direction', 'no', 'NO', 'blocker'),
    ('three', 'direction', 'hold', '보류', 'hold'),
    ('three', 'direction', 'yes', 'YES', 'opening'),
    ('celtic', 'celtic-cross', 'present', '현재 상황', 'present'),
    ('celtic', 'celtic-cross', 'obstacle', '장애물', 'blocker'),
    ('celtic', 'celtic-cross', 'root', '내면의 원인', 'context'),
    ('celtic', 'celtic-cross', 'goal', '의식적인 바람', 'context'),
    ('celtic', 'celtic-cross', 'past', '지나간 영향', 'past'),
    ('celtic', 'celtic-cross', 'near-future', '다가오는 흐름', 'future'),
    ('celtic', 'celtic-cross', 'self', '나의 태도', 'context'),
    ('celtic', 'celtic-cross', 'environment', '주변 환경', 'context'),
    ('celtic', 'celtic-cross', 'hopes-fears', '희망과 두려움', 'context'),
    ('celtic', 'celtic-cross', 'outcome', '최종 흐름', 'future'),
    ('horoscope', 'twelve-houses', 'self', '나 자신', 'present'),
    ('horoscope', 'twelve-houses', 'money', '재정', 'context'),
    ('horoscope', 'twelve-houses', 'communication', '소통', 'context'),
    ('horoscope', 'twelve-houses', 'home', '가정', 'context'),
    ('horoscope', 'twelve-houses', 'creativity', '창의성', 'context'),
    ('horoscope', 'twelve-houses', 'routine', '일상과 건강', 'context'),
    ('horoscope', 'twelve-houses', 'partnership', '파트너십', 'context'),
    ('horoscope', 'twelve-houses', 'transformation', '변화와 전환', 'context'),
    ('horoscope', 'twelve-houses', 'growth', '성장과 시야', 'context'),
    ('horoscope', 'twelve-houses', 'career', '진로와 역할', 'context'),
    ('horoscope', 'twelve-houses', 'community', '공동체', 'context'),
    ('horoscope', 'twelve-houses', 'inner-world', '내면의 세계', 'context')
), sources as (
  select
    profile.card_id,
    profile.suit,
    topic.topic_id,
    orientation.value as orientation,
    position.reading_type,
    position.layout_id,
    position.position_id,
    position.label,
    position.role,
    case orientation.value
      when 'upright' then base.upright
      else base.reversed
    end as meaning
  from tarot_card_profiles as profile
  join tarot_base_interpretations as base on base.card_id = profile.card_id
  cross join (values ('upright'::tarot_orientation), ('reversed'::tarot_orientation)) as orientation(value)
  cross join (values
    ('their-feelings'),
    ('new-love'),
    ('relationship-flow'),
    ('career'),
    ('money'),
    ('relationships'),
    ('decision'),
    ('personal-flow')
  ) as topic(topic_id)
  cross join position_definitions as position
), prepared_sources as (
  select
    *,
    case topic_id
      when 'their-feelings' then meaning ->> 'love'
      when 'new-love' then meaning ->> 'love'
      when 'relationship-flow' then meaning ->> 'love'
      when 'career' then meaning ->> 'career'
      when 'money' then meaning ->> 'cause'
      when 'relationships' then meaning ->> 'relationships'
      when 'decision' then meaning ->> 'cause'
      when 'personal-flow' then meaning ->> 'overview'
    end as topic_meaning,
    case
      when topic_id <> 'career' then ''
      when suit = 'wands' then '프로젝트를 시작하거나 주도권을 잡는 장면에서 이 흐름이 특히 선명해져요.'
      when suit = 'cups' then '동료와의 협업, 팀 안의 신뢰를 조율하는 장면에서 이 흐름이 특히 선명해져요.'
      when suit = 'swords' then '평가·면접·시험 또는 갈등을 마주한 장면에서 이 흐름이 특히 선명해져요.'
      when suit = 'pentacles' then '기술과 결과, 급여나 성적을 점검하는 장면에서 이 흐름이 특히 선명해져요.'
      else '역할을 바꾸거나 일의 방향을 다시 정하는 장면에서 이 흐름이 특히 선명해져요.'
    end as career_scene
  from sources
)
insert into tarot_position_readings (
  card_id,
  topic_id,
  orientation,
  reading_type,
  layout_id,
  position_id,
  headline,
  summary,
  detail,
  advice,
  reflection_question
)
select
  card_id,
  topic_id,
  orientation,
  reading_type,
  layout_id,
  position_id,
  format('%s에서 마주한 흐름', label),
  case role
    when 'past' then concat_ws(' ',
      coalesce(topic_meaning, meaning ->> 'cause'),
      format('%s의 장면은 이미 지나갔지만, 지금의 선택에 조용히 영향을 남겼어요.', label)
    )
    when 'present' then concat_ws(' ',
      coalesce(topic_meaning, meaning ->> 'current_situation'),
      format('%s에서는 지금 드러나는 흐름을 있는 그대로 살펴보세요.', label)
    )
    when 'future' then concat_ws(' ',
      coalesce(meaning ->> 'future', topic_meaning),
      format('%s의 흐름은 현재를 돌본다면 가능성으로 이어질 수 있어요.', label)
    )
    when 'blocker' then concat_ws(' ',
      coalesce(meaning ->> 'current_situation', topic_meaning),
      format('%s에서는 지금 이 신호를 피하고 멈춰 확인해야 해요.', label)
    )
    when 'hold' then concat_ws(' ',
      coalesce(meaning ->> 'cause', topic_meaning),
      format('%s에서는 결정을 미루고 사실과 신호를 먼저 확인하세요.', label)
    )
    when 'opening' then concat_ws(' ',
      coalesce(meaning ->> 'advice', topic_meaning),
      format('%s에서는 이 조건이 갖춰진다면 조심스럽게 진행해도 좋아요.', label)
    )
    when 'advice' then concat_ws(' ',
      coalesce(meaning ->> 'advice', topic_meaning),
      format('%s에서는 이 조언을 오늘의 작은 행동으로 옮겨 보세요.', label)
    )
    when 'context' then concat_ws(' ',
      coalesce(topic_meaning, meaning ->> 'overview'),
      format('%s의 배경을 차분히 살피면 지금의 마음이 더 또렷해져요.', label)
    )
    else concat_ws(' ',
      coalesce(topic_meaning, meaning ->> 'overview'),
      format('%s에서 비친 장면을 오늘의 현실과 다정하게 연결해 보세요.', label)
    )
  end,
  concat_ws(' ',
    coalesce(topic_meaning, meaning ->> 'overview'),
    career_scene,
    case role
      when 'past' then '그때의 선택과 감정이 오늘까지 이어졌던 이유를 천천히 살펴보세요.'
      when 'present' then '지금 눈앞의 반응과 조건을 있는 그대로 확인할수록 길이 선명해져요.'
      when 'future' then '서두르기보다 현재의 흐름을 돌보면 다음 장면을 더 편안하게 맞이할 수 있어요.'
      when 'blocker' then '불편한 신호를 무시한 채 밀어붙이지 않는 것이 먼저예요.'
      when 'hold' then '확신이 서지 않는 부분은 자료와 대화를 통해 검증한 뒤 정해도 늦지 않아요.'
      when 'opening' then '준비가 갖춰졌는지 확인했다면 작은 단계부터 길을 열어 보세요.'
      else '카드가 비추는 장면을 현재의 현실과 연결해 보세요.'
    end
  ),
  case role
    when 'blocker' then '지금은 피해야 할 조건을 분명히 적고, 그 조건이 사라지기 전에는 속도를 줄이세요.'
    when 'hold' then '결정을 미루고 필요한 정보와 상대의 실제 반응을 하나씩 확인하세요.'
    when 'opening' then '진행하기 전에 준비된 조건을 확인하고, 감당 가능한 작은 행동부터 시작하세요.'
    when 'past' then '과거의 장면에서 아직 붙잡고 있는 기대가 무엇인지 살펴보고 오늘의 선택을 새로 정하세요.'
    when 'future' then '다가올 가능성을 붙잡으려 하기보다 오늘 할 수 있는 준비를 하나만 골라 해보세요.'
    else coalesce(meaning ->> 'advice', '지금 가장 솔직한 마음을 살피고, 무리하지 않는 한 걸음을 선택하세요.')
  end,
  case role
    when 'past' then format('%s에서 지나갔지만 아직 내 선택에 남아 있는 것은 무엇일까요?', label)
    when 'present' then format('%s에서 지금 가장 분명하게 확인할 수 있는 사실은 무엇일까요?', label)
    when 'future' then format('%s의 가능성을 위해 오늘 내가 준비할 수 있는 한 가지는 무엇일까요?', label)
    when 'blocker' then format('%s에서 내가 피하거나 멈춰야 할 신호는 무엇일까요?', label)
    when 'hold' then format('%s에서 결정을 미루고 먼저 검증할 정보는 무엇일까요?', label)
    when 'opening' then format('%s에서 진행하기 전에 갖춰야 할 조건은 무엇일까요?', label)
    else format('%s에서 내 마음이 놓치지 말아야 할 장면은 무엇일까요?', label)
  end
from prepared_sources
on conflict (card_id, topic_id, orientation, reading_type, layout_id, position_id)
do update set
  headline = excluded.headline,
  summary = excluded.summary,
  detail = excluded.detail,
  advice = excluded.advice,
  reflection_question = excluded.reflection_question;

do $$
begin
  if (select count(*) from tarot_position_readings) <> 47424 then
    raise exception 'Expected 47424 position readings';
  end if;
end
$$;
