create table if not exists tarot_count_logs (
  id bigint generated by default as identity primary key,
  reached_at timestamptz not null default now()
);

alter table tarot_count_logs enable row level security;

drop policy if exists "result arrivals are publicly recordable" on tarot_count_logs;
create policy "result arrivals are publicly recordable"
on tarot_count_logs
for insert
to anon, authenticated
with check (true);

drop policy if exists "result arrival count is publicly readable" on tarot_count_logs;
create policy "result arrival count is publicly readable"
on tarot_count_logs
for select
to anon, authenticated
using (true);
